on: push
name: run_tests
jobs:
  gitHubActionForPytest:
    name: GitHub Action for pytest
    #runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: vai
        uses: docker://joyzoursky/python-chromedriver
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install selenium
          pip install pytest-html
          cd ./tests
          py.test --browser_name chrome --html=Reports/reports.html
#      - name: Test with pytest
#        working-directory: ./tests
#        run: |
#          py.test --browser_name chrome --html=Reports/reports.html



