on: push
name: run_tests
jobs:
 gitHubActionForPytest:
   name: GitHub Action for pytest
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install selenium
        pip install pytest-html
        pip install webdriver_manager

        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add - \
        && echo "deb https://dl.google.com/linux/chrome/deb/ stable main" | sudo tee -a /etc/apt/sources.list.d/google-chrome.list \
        && sudo apt-get update -qqy \
        && sudo apt-get -qqy install google-chrome-unstable \
        && sudo rm /etc/apt/sources.list.d/google-chrome.list \
        && sudo rm -rf /var/lib/apt/lists/* /var/cache/apt/*
   

    - name: Test with pytest
      working-directory: ./tests
      run: |
        py.test --browser_name chrome --html=./reports/reports.html



 gitHubCreatesdoc:
   name: Test run report
     runs-on: ubuntu-latest
     steps:
       - name: Upload report tests
         uses: actions/upload-artifact@v2
         with:
           name: report
           path: //home/runner/work/test_automation_saucedemo/test_automation_saucedemo/tests/Reports/reports.html