on: push
name: run_tests
jobs:
  gitHubActionForPytest:
    name: GitHub Action for pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install selenium
          pip install pytest-html
      - name: Install browser dependencies
        run: |
          sudo apt-get install chromium-chromedriver
          sudo find / -name "chromedriver"
          echo $PATH
#      - name: Install Chrome and Firefox.
#        run: |
#          sudo apt install google-chrome-stable
#          sudo apt-get install firefox
#      - name: Install chromedriver and geckodriver (Firefox Webdriver)
#        run: |
#          seleniumbase install chromedriver
#          seleniumbase install geckodriver
      - name: Test with pytest
        working-directory: ./tests
        run: |
          py.test --browser_name chrome --html=Reports/reports.html



