on: push
name: run_tests
jobs:
 gitHubActionForPytest:
   name: GitHub Action for pytest
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install selenium
        pip install pytest-html
        sudo curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add
        sudo echo "deb https://dl.google.com/linux/chrome/deb/ stable main" | sudo tee -a /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get -y update
        sudo apt-get -y install google-chrome-stable
    - name: Prepare Selenium
      uses: nanasess/setup-chromedriver@master
    - name: Test with pytest
      working-directory: ./tests
      run: |
        py.test --browser_name chrome --html=Reports/reports.html
